url: "https://taprs.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Nikita Tikhomirov" # the name of your site, e.g. ACME Corp.

collections:
  science:
    output: true
  trips:
    output: true
